spring:
  task:
    scheduling:
      pool:
        size: 30

  datasource:
    url: jdbc:postgresql://localhost:6432/rm
    username: appuser
    password: postgres
    driverClassName: org.postgresql.Driver
    hikari:
      maximumPoolSize: 50

  sql:
    init:
      mode: always

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: cases
        jdbc:
          batch_size: 1000
          order_inserts: true
          lob:
            non_contextual_creation: true

  cloud:
    gcp:
      pubsub:
        subscriber:
          flow-control:
            max-outstanding-element-count: 100

queueconfig:
  case-update-subscription: event_case-update_rm-fieldwork-adapter
  fieldwork-action-instruction-topic: event_fieldwork_action-instruction
  publishtimeout: 30  # In seconds

healthcheck:
  frequency: 15000 #milliseconds
  filename: /tmp/fieldwork-adapter-healthy

exceptionmanager:
  connection:
    scheme: http
    host: localhost
    port: 8666

messagelogging:
  logstacktraces: false

logging:
  profile: DEV
  level:
    root: INFO
    com.google.cloud.spring.pubsub.integration.inbound.PubSubInboundChannelAdapter: ERROR

scheduler:
  frequency: 1000 #milliseconds
  chunksize: 1000
  leaderDeathTimeout: 120 #seconds


